// <auto-generated />
using LogicServer.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogicServer.Migrations
{
    [DbContext(typeof(DnDDbContext))]
    [Migration("20240109093938_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogicServer.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("integer");

                    b.Property<int>("MinDamage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weapon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 19,
                            AttackModifier = 18,
                            AttackPerRound = 1,
                            DamageModifier = 4,
                            HitPoints = 52,
                            MaxDamage = 8,
                            MinDamage = 1,
                            Name = "Hellwasp",
                            Weapon = 0
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 12,
                            AttackModifier = 18,
                            AttackPerRound = 2,
                            DamageModifier = 4,
                            HitPoints = 59,
                            MaxDamage = 6,
                            MinDamage = 2,
                            Name = "Griffon",
                            Weapon = 0
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 14,
                            AttackModifier = 12,
                            AttackPerRound = 1,
                            DamageModifier = 1,
                            HitPoints = 42,
                            MaxDamage = 8,
                            MinDamage = 2,
                            Name = "Vampirate",
                            Weapon = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
